"""Modelos de FiscalAPI."""

from .common_models import (
    ApiResponse,
    BaseDto,
    CatalogDto,
    FiscalApiSettings,
    PagedList,
    ValidationFailure,
)
from .carta_porte_models import (
    # Carta Porte models
    UbicacionDomicilio,
    TipoFiguraDomicilio,
    RegimenAduanero,
    Ubicacion,
    DocumentoAduanero,
    GuiaIdentificacion,
    CantidadTransporta,
    DetalleMercancia,
    Mercancia,
    Remolque,
    Autotransporte,
    RemolqueCCP,
    ContenedorMaritimo,
    TransporteMaritimo,
    TransporteAereo,
    DerechoDePaso,
    CarroContenedor,
    Carro,
    TransporteFerroviario,
    ParteTransporte,
    TipoFigura,
    CartaPorteComplement,
)
from .comercio_exterior_models import (
    # Comercio Exterior models
    ComercioExteriorEmisorDomicilio,
    ComercioExteriorReceptorDomicilio,
    ComercioExteriorDestinatarioDomicilio,
    ComercioExteriorEmisor,
    ComercioExteriorPropietario,
    ComercioExteriorReceptor,
    ComercioExteriorDestinatario,
    ComercioExteriorMercanciaDescripcionEspecifica,
    ComercioExteriorMercancia,
    ComercioExteriorComplement,
)
from .manifest_models import (
    # Manifest models
    SignManifestRequest,
    SignManifestResponse,
)
from .fiscalapi_models import (
    # Product models
    ProductTax,
    Product,
    # Person models
    Person,
    EmployeeData,
    EmployerData,
    TaxFile,
    # Invoice issuer/recipient models
    InvoiceIssuerEmployerData,
    InvoiceRecipientEmployeeData,
    TaxCredential,
    InvoiceIssuer,
    InvoiceRecipient,
    # Invoice item models
    ItemTax,
    ItemOnBehalfOf,
    ItemCustomsInfo,
    ItemPropertyInfo,
    ItemPart,
    InvoiceItem,
    # Invoice related models
    GlobalInformation,
    RelatedInvoice,
    PaidInvoiceTax,
    PaidInvoice,
    InvoicePayment,
    # Complement models
    LocalTax,
    LocalTaxesComplement,
    PaymentComplement,
    PayrollStockOptions,
    PayrollOvertime,
    PayrollEarning,
    PayrollBalanceCompensation,
    PayrollOtherPayment,
    PayrollRetirement,
    PayrollSeverance,
    PayrollEarningsComplement,
    PayrollDeduction,
    PayrollDisability,
    PayrollComplement,
    CartaPorteComplement,
    InvoiceComplement,
    # Invoice models
    InvoiceResponse,
    Invoice,
    CancelInvoiceRequest,
    CancelInvoiceResponse,
    CreatePdfRequest,
    FileResponse,
    SendInvoiceRequest,
    InvoiceStatusRequest,
    InvoiceStatusResponse,
    # API Key models
    ApiKey,
    # Download models
    DownloadRule,
    DownloadRequest,
    MetadataItem,
    # XML models
    XmlGlobalInformation,
    XmlIssuer,
    XmlRecipient,
    XmlRelated,
    XmlTax,
    XmlItemCustomsInformation,
    XmlItemPropertyAccount,
    XmlItemTax,
    XmlItem,
    XmlComplement,
    Xml,
    # Stamp models
    UserLookupDto,
    StampTransaction,
    StampTransactionParams,
)

__all__ = [
    # common_models
    "ApiResponse",
    # Carta Porte models
    "UbicacionDomicilio",
    "TipoFiguraDomicilio",
    "RegimenAduanero",
    "Ubicacion",
    "DocumentoAduanero",
    "CantidadTransporta",
    "DetalleMercancia",
    "Mercancia",
    "Remolque",
    "Autotransporte",
    "RemolqueCCP",
    "ContenedorMaritimo",
    "TransporteMaritimo",
    "TransporteAereo",
    "DerechoDePaso",
    "CarroContenedor",
    "Carro",
    "TransporteFerroviario",
    "ParteTransporte",
    "TipoFigura",
    "CartaPorteComplement",
    # Comercio Exterior models
    "ComercioExteriorEmisorDomicilio",
    "ComercioExteriorReceptorDomicilio",
    "ComercioExteriorDestinatarioDomicilio",
    "ComercioExteriorEmisor",
    "ComercioExteriorPropietario",
    "ComercioExteriorReceptor",
    "ComercioExteriorDestinatario",
    "ComercioExteriorMercanciaDescripcionEspecifica",
    "ComercioExteriorMercancia",
    "ComercioExteriorComplement",
    "BaseDto",
    "CatalogDto",
    "FiscalApiSettings",
    "PagedList",
    "ValidationFailure",
    # Product models
    "ProductTax",
    "Product",
    # Person models
    "Person",
    "EmployeeData",
    "EmployerData",
    "TaxFile",
    # Invoice issuer/recipient models
    "InvoiceIssuerEmployerData",
    "InvoiceRecipientEmployeeData",
    "TaxCredential",
    "InvoiceIssuer",
    "InvoiceRecipient",
    # Invoice item models
    "ItemTax",
    "ItemOnBehalfOf",
    "ItemCustomsInfo",
    "ItemPropertyInfo",
    "ItemPart",
    "InvoiceItem",
    # Invoice related models
    "GlobalInformation",
    "RelatedInvoice",
    "PaidInvoiceTax",
    "PaidInvoice",
    "InvoicePayment",
    # Complement models
    "LocalTax",
    "LocalTaxesComplement",
    "PaymentComplement",
    "PayrollStockOptions",
    "PayrollOvertime",
    "PayrollEarning",
    "PayrollBalanceCompensation",
    "PayrollOtherPayment",
    "PayrollRetirement",
    "PayrollSeverance",
    "PayrollEarningsComplement",
    "PayrollDeduction",
    "PayrollDisability",
    "PayrollComplement",
    "CartaPorteComplement",
    "InvoiceComplement",
    # Invoice models
    "InvoiceResponse",
    "Invoice",
    "CancelInvoiceRequest",
    "CancelInvoiceResponse",
    "CreatePdfRequest",
    "FileResponse",
    "SendInvoiceRequest",
    "InvoiceStatusRequest",
    "InvoiceStatusResponse",
    # API Key models
    "ApiKey",
    # Download models
    "DownloadRule",
    "DownloadRequest",
    "MetadataItem",
    # XML models
    "XmlGlobalInformation",
    "XmlIssuer",
    "XmlRecipient",
    "XmlRelated",
    "XmlTax",
    "XmlItemCustomsInformation",
    "XmlItemPropertyAccount",
    "XmlItemTax",
    "XmlItem",
    "XmlComplement",
    "Xml",
    # Stamp models
    "UserLookupDto",
    "StampTransaction",
    "StampTransactionParams",
    # Manifest models
    "SignManifestRequest",
    "SignManifestResponse",
]
